version: "3"
services:
  portfolio:
    image: node:18
    ports:
      - "3000:3000"
    networks:
      - ec2-network
    volumes:
      - ./portfolio:/app
    working_dir: /app
    command: "npm run start"

networks:
  ec2-network:
    external: true
