version: "3"
services:
  portfolio:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ec2-network

networks:
  ec2-network:
    external: true
