name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main # 可以根据你的实际情况调整分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_USER: ${{ secrets.AWS_USER }}
      AWS_SERVER: ${{ secrets.AWS_SERVER }}
      AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}" >> .env.local
          echo "RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }}" >> .env.local
          echo "CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }}" >> .env.local
          echo "CONTACT_PASSWORD=${{ secrets.CONTACT_PASSWORD }}" >> .env.local

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_SERVER }}
          REMOTE_USER: ${{ secrets.AWS_USER }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          TARGET: "/home/ec2-user/portfolio/"

      - name: Start the project
        run: |
          echo "${AWS_PRIVATE_KEY}" > private_key && chmod 400 private_key

          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_USER}@${AWS_SERVER} "
            docker-compose -f portfolio/docker-compose.yml down &&
            docker-compose -f portfolio/docker-compose.yml up -d
          "
